Add DataSet component to channel layout
GoteoFoundation/goteo pull request #368
Opened 2022-03-08 14:43 UTC by davidbeig

2022-05-02 09:43 UTC, javicarrillo commented
There are conflicts to resolve @davidbeig.

2022-05-02 10:23 UTC, javicarrillo requested changes

2022-05-02 10:23 UTC, javicarrillo commented on Resources/templates/responsive/channel/partials/data_sets.php
> +        <h2 class="title"><?= $section->main_title ?></h2>
This title should be centered

2022-06-21 13:52 UTC, javicarrillo commented on Resources/templates/responsive/channel/partials/data_sets.php
> +?>
I would add an "if" because the section could be active but empty the datasets channel

2022-06-21 13:52 UTC, javicarrillo commented on Resources/templates/responsive/channel/partials/data_sets.php
> +        <?= $this->insert('partials/components/data_sets', ['dataSets' => $this->dataSets]) ?>
I would change the data_sets component, in mobile the item should be 100% width.

2022-07-04 10:58 UTC, carlos-mg89 commented on src/Goteo/Model/Node/NodeSections.php
> +   * @return  NodeSections
This @return comments isn't necessary, since there's already a return parameter in this method

2022-07-05 15:44 UTC, javicarrillo approved these changes

2022-07-05 15:44 UTC, merged