Add origin register in profile form
GoteoFoundation/goteo pull request #438
Opened 2022-05-30 10:09 UTC by javicarrillo

Add origin register in user profile

2022-05-30 13:59 UTC, carlos-mg89 commented on translations/en/profile.yml
> +profile-field-origin-register-previous-project: 'Una campaña en Goteo anterior'
This translations is in Spanish

2022-05-30 14:00 UTC, carlos-mg89 commented on translations/en/profile.yml
> +profile-field-origin-register-search: 'A previous Goteo campaign'
I think this translation should be "Using a search engine". And actually, looks like this translation is for `profile-field-origin-register-previous-project` translation.

2022-05-31 14:15 UTC, davidbeig requested changes
Well done! I just left a commend, since Carlos had already requested some changes.

At first i understood that this PR was for the origins of projects, not of users.

Also, are we planning to have some charts about the origins of users in the near future?

2022-05-31 14:15 UTC, davidbeig commented on src/Goteo/Library/Forms/Model/UserProfileForm.php
> +                'constraints' => $this->getConstraints('origin_register'),
It does not have any constraint, so we could remove this.

2022-06-27 07:50 UTC, merged