Enable full Symfony controllers
GoteoFoundation/goteo pull request #463
Opened 2022-06-29 09:40 UTC by carlos-mg89

A new base controller has been added that extends a Symfony base controller class (`AbstractController`).

This new `BaseSymfonyController`, allows rendering only Foil templates. Although the idea is that it will render Twig templates in a near future as well.

2022-06-29 11:02 UTC, carlos-mg89 commented on src/Routes/misc_routes.php
> +));
At the moment, I wasn't able to load controller actions using Symfony Route annotations. Perhaps in another task...

2022-06-29 11:03 UTC, carlos-mg89 commented on src/Goteo/Controller/TestController.php
> +class TestController extends BaseSymfonyController {
This controller should be removed before accepting the PR. It's just to ease the testing of it.

2022-07-15 09:43 UTC, carlos-mg89 commented on src/Goteo/Controller/BaseSymfonyController.php
> +    }
This should be removed when the project gets ridden of the current DB class

2022-07-15 09:43 UTC, carlos-mg89 commented on src/Routes/misc_routes.php
> +));
To be removed before merging PR

2022-07-18 11:03 UTC, davidbeig requested changes
Good job @carlos-mg89 !

I have tested the new endpoints created and they work correctly. I think we can move on to delete those endpoints and plan new developments with this new controller

2022-07-18 11:03 UTC, davidbeig commented on src/routes.php
> +));
Why duplicate this route?

2022-07-18 11:54 UTC, carlos-mg89 commented on src/routes.php
> +));
That's something that should be fixed in a future. The 'home' route is somehow not available to the `Router` / `UrlGenerator`.

When I added this new_home endpoint, it worked. So I guess there's some issue with either naming a route 'home' or with the route path being '/'.

If you prefer so, we could simply remove the newly created 'new_home'. Just be aware that 'home' is not working.

2022-07-18 14:59 UTC, davidbeig approved these changes
Thanks for the changes! I'm approving it now :)

2022-07-18 14:59 UTC, merged