Feature Creator
GoteoFoundation/goteo pull request #580
Opened 2023-11-20 16:59 UTC by davidbeig

#### :tophat: What? Why?
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #568 #579 #571 

#### Testing
*Describe the best way to test or validate your PR.*

### :camera: Screenshots
*Please add screenshots of the changes you are proposing*
![Description](URL)

:hearts: Thank you!

2023-11-22 13:40 UTC, subiabre requested changes

2023-11-22 13:40 UTC, subiabre commented on Resources/templates/responsive/channel/call/partials/video.php
Why does this template exist?

2023-11-22 13:40 UTC, subiabre commented on src/Goteo/Controller/CreatorController.php
> +        /*
I think we should also redirect to the user-profile route for non-creators.

2023-12-11 15:31 UTC, davidbeig commented on Resources/templates/responsive/channel/call/partials/video.php
You are right, it's not part of this PR

2023-12-12 11:49 UTC, merged